# Generated by Django 4.2.20 on 2025-04-30 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cedula', message='La cédula debe contener solo números.', regex='^\\d+$')])),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_celular', message='El número de celular debe contener solo números.', regex='^\\d+$')])),
                ('plan', models.CharField(choices=[('Básico', 'Plan Básico'), ('Estándar', 'Plan Estándar'), ('Premium', 'Plan Premium')], max_length=20)),
                ('horario', models.CharField(choices=[('Mañana', 'Mañana (8:00 AM - 12:00 PM)'), ('Tarde', 'Tarde (2:00 PM - 6:00 PM)')], max_length=10)),
                ('foto_cedula', models.FileField(upload_to='documentos/cedulas/')),
                ('recibo_publico', models.FileField(upload_to='documentos/recibos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cedula', message='La cédula debe contener solo números.', regex='^\\d+$')])),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El número de teléfono debe contener solo números.', regex='^\\d+$')])),
                ('correo', models.EmailField(max_length=254)),
                ('barrio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('plan_seleccionado', models.CharField(choices=[('Internet 50MB', 'Internet 50MB'), ('Internet 100MB', 'Internet 100MB'), ('Internet 200MB', 'Internet 200MB'), ('Internet 500MB', 'Internet 500MB'), ('Fibra Óptica 1GB', 'Fibra Óptica 1GB')], max_length=50)),
                ('preferencia_horario', models.CharField(choices=[('Mañana (8:00-12:00)', 'Mañana (8:00-12:00)'), ('Tarde (13:00-17:00)', 'Tarde (13:00-17:00)'), ('Noche (18:00-20:00)', 'Noche (18:00-20:00)')], max_length=50)),
                ('url_cedula', models.URLField(max_length=500)),
                ('url_recibo', models.URLField(max_length=500)),
                ('instalador', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_instalacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
            },
        ),
    ]
